config/routes.rb
Myapp::Application.routes.draw do

 resources :questions do
  end

  root "welcome#index"

	
  

end

app/models/question.rb
class Question < ActiveRecord::Base
	validates :question, presence: true,
							length: { minimum: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

	def new
	@question = Question.new
	end

	def create
		@question = Question.new(params[:question].permit(:question))
		
		if @question.save
			redirect_to @question
		else
			render 'new'
		end
		#@question.save
		#redirect_to @question
		#render text: params[:question].inspect
	end

	def index
		@questions = Question.all
	end
	
	def show
		@question = Question.find(params[:id])
	end

	
	private
	
		def question_params
			params.require(:question).permit(:question)
		end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Myapp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/questions/new.html.erb
<h1> Yeni soru buradan sorulur </h1>
<%= form_for :question, url: questions_path do |f| %>
	<% if @question.errors.any? %>
	<div id="error_explanation">
		<h2><%= pluralize(@question.errors.count, "error") %> prohibited this post from being saved: </h2>
	<ul>
	<% @question.er.full_messages.each do |msg| %>
		<li><%= msg %></li>
<% end %>
	</ul>
	</div>
	<% end %>
	<p>
	<%= f.label :question %><br>
	<%= f.text_field :question %>
	</p>
	<p>
		<%= f.submit %>
	</p>
<% end %>
<%= link_to 'back', questions_path %>

app/views/questions/show.html.erb
<p>
	<strong>Soru: </strong>
	<%= @question.question %>
</p>

app/views/welcome/index.html.erb
<h2>Hello World</h2>
<p>
	The time is now: <%= Time.now %>
	</br>
	Thank you for visiting.
</p>